### ISSUE TITLE
Incorrect climbing position if previous climbing was interrupt

### ISSUE THREAD

**Issue by smartblade** [smartblade/BldPatch#1]
See video provided by @sryml (https://youtu.be/M3wmhNLCZ18).
To reproduce
- Open game witch console (`Blade.exe -console`)
- Start climbing by jump button pressing. Open menu immediately
- Write `char.Wuea=0; char.LaunchAnmType("hurt_f_big")` to console
- Go back to the game. The next climbings "teleport" you to previous one.

**Comment by smartblade** [comment]
Fixed in 3596af3

**Comment by tansy** [comment]
[FWIW](https://en.wiktionary.org/wiki/for_what_it%27s_worth#English), verb [find](https://dictionary.cambridge.org/dictionary/english/find) is irregular and perfective form is found, not founded.
So I suggest to change it in a future as it is shown in the [patch](https://pastebin.com/nd953t7G).

**Comment by smartblade** [comment]
Thanks, @tansy. I'll change it later.
